
---
- name: Test Notification
  hosts: all

  tasks:
    - name: Update and upgrade apt packages  
      ansible.builtin.uri:
        url: "https://notify.federicohome.com/message?token=A_c68XWoVfwsa63"
        method: POST
        body_format: json
        body:
          title: Ansible Test
          message: "Disk space on {{ inventory_hostname }} is above 90%!"
