---
- name: Add ssh key
  hosts: all
  become: true

  tasks:
    - name: Change sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%yoda'
        line: '%yoda ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
